import { type User, type InsertUser, type Transaction, type InsertTransaction, type Card, type InsertCard, type CryptoAsset, type InsertCryptoAsset } from "@shared/schema";
import { randomUUID } from "crypto";

export interface IStorage {
  getUser(id: string): Promise<User | undefined>;
  getUserByUsername(username: string): Promise<User | undefined>;
  createUser(user: InsertUser): Promise<User>;
  getUserTransactions(userId: string): Promise<Transaction[]>;
  createTransaction(transaction: InsertTransaction): Promise<Transaction>;
  getUserCards(userId: string): Promise<Card[]>;
  createCard(card: InsertCard): Promise<Card>;
  getCryptoAssets(): Promise<CryptoAsset[]>;
  updateCryptoAsset(asset: CryptoAsset): Promise<CryptoAsset>;
}

export class MemStorage implements IStorage {
  private users: Map<string, User>;
  private transactions: Map<string, Transaction>;
  private cards: Map<string, Card>;
  private cryptoAssets: Map<string, CryptoAsset>;

  constructor() {
    this.users = new Map();
    this.transactions = new Map();
    this.cards = new Map();
    this.cryptoAssets = new Map();
    this.seedData();
  }

  private seedData() {
    // Create Thomas Francis user
    const thomasId = randomUUID();
    const thomas: User = {
      id: thomasId,
      username: "thomas.francis",
      firstName: "Thomas",
      lastName: "Francis",
      email: "thomas@example.com",
      avatar: "TF",
      balance: "2.19",
      currency: "AUD",
      plan: "Personal",
      createdAt: new Date(),
    };
    this.users.set(thomasId, thomas);

    // Create cards
    const originalCard: Card = {
      id: randomUUID(),
      userId: thomasId,
      type: "original",
      name: "Original",
      lastFour: "1234",
      isActive: true,
      description: "Fully activate card",
      createdAt: new Date(),
    };

    const disposableCard: Card = {
      id: randomUUID(),
      userId: thomasId,
      type: "disposable",
      name: "Disposable",
      lastFour: "5678",
      isActive: true,
      description: "Regenerates details after each use",
      createdAt: new Date(),
    };

    this.cards.set(originalCard.id, originalCard);
    this.cards.set(disposableCard.id, disposableCard);

    // Create transactions - New transaction data from June-July 2024 European trip
    const transactions: Omit<Transaction, 'id'>[] = [
      {
        userId: thomasId,
        merchant: "Taxi G7",
        amount: "-45.45",
        currency: "AUD",
        originalAmount: "-25.00",
        originalCurrency: "EUR",
        category: "Transport",
        status: "completed",
        description: "18:22 • -A$45.45",
        date: new Date("2024-07-26T18:22:00"),
        merchantIcon: "TG",
        iconColor: "#0066CC",
      },
      {
        userId: thomasId,
        merchant: "Galeries Lafayette Haussmann",
        amount: "-1374.55",
        currency: "AUD",
        originalAmount: "-756.00",
        originalCurrency: "EUR",
        category: "Shopping",
        status: "completed",
        description: "15:47 • -A$1374.55",
        date: new Date("2024-07-26T15:47:00"),
        merchantIcon: "GL",
        iconColor: "#DC2626",
      },
      {
        userId: thomasId,
        merchant: "L'Ami Jean",
        amount: "-178.18",
        currency: "AUD",
        originalAmount: "-98.00",
        originalCurrency: "EUR",
        category: "Food & Drink",
        status: "completed",
        description: "12:15 • -A$178.18",
        date: new Date("2024-07-26T12:15:00"),
        merchantIcon: "LJ",
        iconColor: "#FB923C",
      },
      {
        userId: thomasId,
        merchant: "Café de Flore",
        amount: "-63.64",
        currency: "AUD",
        originalAmount: "-35.00",
        originalCurrency: "EUR",
        category: "Food & Drink",
        status: "completed",
        description: "08:35 • -A$63.64",
        date: new Date("2024-07-26T08:35:00"),
        merchantIcon: "CD",
        iconColor: "#FB923C",
      },
      {
        userId: thomasId,
        merchant: "SNCF Connect",
        amount: "-178.18",
        currency: "AUD",
        originalAmount: "-98.00",
        originalCurrency: "EUR",
        category: "Shopping",
        status: "completed",
        description: "17:18 • -A$178.18",
        date: new Date("2024-07-25T17:18:00"),
        merchantIcon: "SC",
        iconColor: "#DC2626",
      },
      {
        userId: thomasId,
        merchant: "Taxi Nice Ville",
        amount: "-98.18",
        currency: "AUD",
        originalAmount: "-54.00",
        originalCurrency: "EUR",
        category: "Transport",
        status: "completed",
        description: "16:33 • -A$98.18",
        date: new Date("2024-07-25T16:33:00"),
        merchantIcon: "TN",
        iconColor: "#0066CC",
      },
      {
        userId: thomasId,
        merchant: "Chez Pipo",
        amount: "-54.55",
        currency: "AUD",
        originalAmount: "-30.00",
        originalCurrency: "EUR",
        category: "Food & Drink",
        status: "completed",
        description: "12:43 • -A$54.55",
        date: new Date("2024-07-25T12:43:00"),
        merchantIcon: "CP",
        iconColor: "#FB923C",
      },
      {
        userId: thomasId,
        merchant: "Galeries Lafayette Nice",
        amount: "-509.09",
        currency: "AUD",
        originalAmount: "-280.00",
        originalCurrency: "EUR",
        category: "Shopping",
        status: "completed",
        description: "11:05 • -A$509.09",
        date: new Date("2024-07-25T11:05:00"),
        merchantIcon: "GL",
        iconColor: "#DC2626",
      },
      {
        userId: thomasId,
        merchant: "RELAY",
        amount: "-8.75",
        currency: "AUD",
        originalAmount: "-4.81",
        originalCurrency: "EUR",
        category: "Food & Drink",
        status: "completed",
        description: "09:48 • -A$8.75",
        date: new Date("2024-07-25T09:48:00"),
        merchantIcon: "RE",
        iconColor: "#FB923C",
      },
      {
        userId: thomasId,
        merchant: "La Petite Maison",
        amount: "-690.91",
        currency: "AUD",
        originalAmount: "-380.00",
        originalCurrency: "EUR",
        category: "Food & Drink",
        status: "completed",
        description: "20:15 • -A$690.91",
        date: new Date("2024-07-24T20:15:00"),
        merchantIcon: "LP",
        iconColor: "#FB923C",
      },
      {
        userId: thomasId,
        merchant: "Maison Auer",
        amount: "-26.36",
        currency: "AUD",
        originalAmount: "-14.50",
        originalCurrency: "EUR",
        category: "Shopping",
        status: "completed",
        description: "16:27 • -A$26.36",
        date: new Date("2024-07-24T16:27:00"),
        merchantIcon: "MA",
        iconColor: "#DC2626",
      },
      {
        userId: thomasId,
        merchant: "Plage Keller",
        amount: "-25.45",
        currency: "AUD",
        originalAmount: "-14.00",
        originalCurrency: "EUR",
        category: "Entertainment",
        status: "completed",
        description: "13:16 • -A$25.45",
        date: new Date("2024-07-24T13:16:00"),
        merchantIcon: "PK",
        iconColor: "#9333EA",
      },
      {
        userId: thomasId,
        merchant: "Plage Keller Sunbeds",
        amount: "-109.09",
        currency: "AUD",
        originalAmount: "-60.00",
        originalCurrency: "EUR",
        category: "Entertainment",
        status: "completed",
        description: "12:05 • -A$109.09",
        date: new Date("2024-07-24T12:05:00"),
        merchantIcon: "PK",
        iconColor: "#9333EA",
      },
      {
        userId: thomasId,
        merchant: "Boulangerie Veziano",
        amount: "-14.73",
        currency: "AUD",
        originalAmount: "-8.10",
        originalCurrency: "EUR",
        category: "Food & Drink",
        status: "completed",
        description: "10:41 • -A$14.73",
        date: new Date("2024-07-24T10:41:00"),
        merchantIcon: "BV",
        iconColor: "#FB923C",
      },
      {
        userId: thomasId,
        merchant: "Lime E-Bike",
        amount: "-7.18",
        currency: "AUD",
        originalAmount: "-3.95",
        originalCurrency: "EUR",
        category: "Entertainment",
        status: "completed",
        description: "21:18 • -A$7.18",
        date: new Date("2024-07-23T21:18:00"),
        merchantIcon: "LE",
        iconColor: "#9333EA",
      },
      {
        userId: thomasId,
        merchant: "Restaurant Miraé by Mauro Colagreco",
        amount: "-338.18",
        currency: "AUD",
        originalAmount: "-186.00",
        originalCurrency: "EUR",
        category: "Food & Drink",
        status: "completed",
        description: "19:42 • -A$338.18",
        date: new Date("2024-07-23T19:42:00"),
        merchantIcon: "RM",
        iconColor: "#FB923C",
      },
      {
        userId: thomasId,
        merchant: "Monoprix Antibes",
        amount: "-16.73",
        currency: "AUD",
        originalAmount: "-9.20",
        originalCurrency: "EUR",
        category: "Food & Drink",
        status: "completed",
        description: "17:04 • -A$16.73",
        date: new Date("2024-07-23T17:04:00"),
        merchantIcon: "MA",
        iconColor: "#FB923C",
      },
      {
        userId: thomasId,
        merchant: "Taxi Nice Côte d'Azur",
        amount: "-136.36",
        currency: "AUD",
        originalAmount: "-75.00",
        originalCurrency: "EUR",
        category: "Transport",
        status: "completed",
        description: "15:18 • -A$136.36",
        date: new Date("2024-07-23T15:18:00"),
        merchantIcon: "TN",
        iconColor: "#0066CC",
      },
      {
        userId: thomasId,
        merchant: "Booking.com",
        amount: "-381.82",
        currency: "AUD",
        originalAmount: "-210.00",
        originalCurrency: "EUR",
        category: "Accommodation",
        status: "completed",
        description: "13:02 • -A$381.82",
        date: new Date("2024-07-23T13:02:00"),
        merchantIcon: "BO",
        iconColor: "#A855F7",
      },
      {
        userId: thomasId,
        merchant: "Taxi Porto Cervo → Olbia",
        amount: "-154.55",
        currency: "AUD",
        originalAmount: "-85.00",
        originalCurrency: "EUR",
        category: "Transport",
        status: "completed",
        description: "11:08 • -A$154.55",
        date: new Date("2024-07-23T11:08:00"),
        merchantIcon: "TP",
        iconColor: "#0066CC",
      },
      {
        userId: thomasId,
        merchant: "Spinnaker Restaurant",
        amount: "-327.27",
        currency: "AUD",
        originalAmount: "-180.00",
        originalCurrency: "EUR",
        category: "Food & Drink",
        status: "completed",
        description: "09:32 • -A$327.27",
        date: new Date("2024-07-23T09:32:00"),
        merchantIcon: "SR",
        iconColor: "#FB923C",
      },
      {
        userId: thomasId,
        merchant: "Uber Porto Cervo",
        amount: "-58.53",
        currency: "AUD",
        originalAmount: "-32.19",
        originalCurrency: "EUR",
        category: "Transport",
        status: "completed",
        description: "23:32 • -A$58.53",
        date: new Date("2024-07-22T23:32:00"),
        merchantIcon: "UP",
        iconColor: "#0066CC",
      },
      {
        userId: thomasId,
        merchant: "Uber Porto Cervo",
        amount: "-129.86",
        currency: "AUD",
        originalAmount: "-71.42",
        originalCurrency: "EUR",
        category: "Transport",
        status: "completed",
        description: "18:03 • -A$129.86",
        date: new Date("2024-07-22T18:03:00"),
        merchantIcon: "UP",
        iconColor: "#0066CC",
      },
      {
        userId: thomasId,
        merchant: "CRAI Porto Cervo",
        amount: "-22.91",
        currency: "AUD",
        originalAmount: "-12.65",
        originalCurrency: "EUR",
        category: "Food & Drink",
        status: "completed",
        description: "16:28 • -A$22.91",
        date: new Date("2024-07-22T16:28:00"),
        merchantIcon: "CP",
        iconColor: "#FB923C",
      },
      {
        userId: thomasId,
        merchant: "Uber Porto Cervo",
        amount: "-143.45",
        currency: "AUD",
        originalAmount: "-78.90",
        originalCurrency: "EUR",
        category: "Transport",
        status: "completed",
        description: "16:02 • -A$143.45",
        date: new Date("2024-07-22T16:02:00"),
        merchantIcon: "UP",
        iconColor: "#0066CC",
      },
      {
        userId: thomasId,
        merchant: "Beach Bar Grande Pevero",
        amount: "-7.64",
        currency: "AUD",
        originalAmount: "-4.20",
        originalCurrency: "EUR",
        category: "Food & Drink",
        status: "completed",
        description: "14:16 • -A$7.64",
        date: new Date("2024-07-22T14:16:00"),
        merchantIcon: "BB",
        iconColor: "#FB923C",
      },
      {
        userId: thomasId,
        merchant: "Beach Bar Grande Pevero",
        amount: "-13.64",
        currency: "AUD",
        originalAmount: "-7.50",
        originalCurrency: "EUR",
        category: "Food & Drink",
        status: "completed",
        description: "12:49 • -A$13.64",
        date: new Date("2024-07-22T12:49:00"),
        merchantIcon: "BB",
        iconColor: "#FB923C",
      },
      {
        userId: thomasId,
        merchant: "Beach Bar Grande Pevero",
        amount: "-6.91",
        currency: "AUD",
        originalAmount: "-3.80",
        originalCurrency: "EUR",
        category: "Food & Drink",
        status: "completed",
        description: "11:04 • -A$6.91",
        date: new Date("2024-07-22T11:04:00"),
        merchantIcon: "BB",
        iconColor: "#FB923C",
      },
      {
        userId: thomasId,
        merchant: "Uber Porto Cervo",
        amount: "-148.95",
        currency: "AUD",
        originalAmount: "-81.42",
        originalCurrency: "EUR",
        category: "Transport",
        status: "completed",
        description: "10:22 • -A$148.95",
        date: new Date("2024-07-22T10:22:00"),
        merchantIcon: "UP",
        iconColor: "#0066CC",
      },
      {
        userId: thomasId,
        merchant: "Poltu Quatu at Phi Beach Club",
        amount: "-167.27",
        currency: "AUD",
        originalAmount: "-92.00",
        originalCurrency: "EUR",
        category: "Food & Drink",
        status: "completed",
        description: "23:49 • -A$167.27",
        date: new Date("2024-07-21T23:49:00"),
        merchantIcon: "PQ",
        iconColor: "#FB923C",
      },
      {
        userId: thomasId,
        merchant: "Poltu Quatu at Phi Beach Club",
        amount: "-65.45",
        currency: "AUD",
        originalAmount: "-36.00",
        originalCurrency: "EUR",
        category: "Food & Drink",
        status: "completed",
        description: "23:21 • -A$65.45",
        date: new Date("2024-07-21T23:21:00"),
        merchantIcon: "PQ",
        iconColor: "#FB923C",
      },
      {
        userId: thomasId,
        merchant: "Poltu Quatu at Phi Beach Club",
        amount: "-65.45",
        currency: "AUD",
        originalAmount: "-36.00",
        originalCurrency: "EUR",
        category: "Food & Drink",
        status: "completed",
        description: "22:58 • -A$65.45",
        date: new Date("2024-07-21T22:58:00"),
        merchantIcon: "PQ",
        iconColor: "#FB923C",
      },
      {
        userId: thomasId,
        merchant: "Poltu Quatu at Phi Beach Club",
        amount: "-65.45",
        currency: "AUD",
        originalAmount: "-36.00",
        originalCurrency: "EUR",
        category: "Food & Drink",
        status: "completed",
        description: "22:36 • -A$65.45",
        date: new Date("2024-07-21T22:36:00"),
        merchantIcon: "PQ",
        iconColor: "#FB923C",
      },
      {
        userId: thomasId,
        merchant: "Phi Beach Restaurant",
        amount: "-868.60",
        currency: "AUD",
        originalAmount: "-477.23",
        originalCurrency: "EUR",
        category: "Food & Drink",
        status: "completed",
        description: "20:45 • -A$868.60",
        date: new Date("2024-07-21T20:45:00"),
        merchantIcon: "PB",
        iconColor: "#FB923C",
      },
      {
        userId: thomasId,
        merchant: "Uber Porto Cervo",
        amount: "-129.86",
        currency: "AUD",
        originalAmount: "-71.42",
        originalCurrency: "EUR",
        category: "Transport",
        status: "completed",
        description: "18:41 • -A$129.86",
        date: new Date("2024-07-21T18:41:00"),
        merchantIcon: "UP",
        iconColor: "#0066CC",
      },
      {
        userId: thomasId,
        merchant: "Café Du Port",
        amount: "-240.00",
        currency: "AUD",
        originalAmount: "-132.00",
        originalCurrency: "EUR",
        category: "Shopping",
        status: "completed",
        description: "14:12 • -A$240.00",
        date: new Date("2024-07-21T14:12:00"),
        merchantIcon: "CD",
        iconColor: "#DC2626",
      },
      {
        userId: thomasId,
        merchant: "Crazy Pizza Porto Cervo",
        amount: "-210.91",
        currency: "AUD",
        originalAmount: "-116.00",
        originalCurrency: "EUR",
        category: "Food & Drink",
        status: "completed",
        description: "12:06 • -A$210.91",
        date: new Date("2024-07-21T12:06:00"),
        merchantIcon: "CP",
        iconColor: "#FB923C",
      },
      {
        userId: thomasId,
        merchant: "Uber Porto Cervo",
        amount: "-136.18",
        currency: "AUD",
        originalAmount: "-74.90",
        originalCurrency: "EUR",
        category: "Transport",
        status: "completed",
        description: "04:14 • -A$136.18",
        date: new Date("2024-07-21T04:14:00"),
        merchantIcon: "UP",
        iconColor: "#0066CC",
      },
      {
        userId: thomasId,
        merchant: "Zuma Porto Cervo",
        amount: "-123.64",
        currency: "AUD",
        originalAmount: "-68.00",
        originalCurrency: "EUR",
        category: "Food & Drink",
        status: "completed",
        description: "01:58 • -A$123.64",
        date: new Date("2024-07-21T01:58:00"),
        merchantIcon: "ZP",
        iconColor: "#FB923C",
      },
      {
        userId: thomasId,
        merchant: "Zuma Porto Cervo",
        amount: "-29.09",
        currency: "AUD",
        originalAmount: "-16.00",
        originalCurrency: "EUR",
        category: "Food & Drink",
        status: "completed",
        description: "01:41 • -A$29.09",
        date: new Date("2024-07-21T01:41:00"),
        merchantIcon: "ZP",
        iconColor: "#FB923C",
      },
      {
        userId: thomasId,
        merchant: "Zuma Porto Cervo",
        amount: "-123.64",
        currency: "AUD",
        originalAmount: "-68.00",
        originalCurrency: "EUR",
        category: "Food & Drink",
        status: "completed",
        description: "01:27 • -A$123.64",
        date: new Date("2024-07-21T01:27:00"),
        merchantIcon: "ZP",
        iconColor: "#FB923C",
      },
      {
        userId: thomasId,
        merchant: "Zuma Porto Cervo",
        amount: "-234.55",
        currency: "AUD",
        originalAmount: "-129.00",
        originalCurrency: "EUR",
        category: "Food & Drink",
        status: "completed",
        description: "01:06 • -A$234.55",
        date: new Date("2024-07-21T01:06:00"),
        merchantIcon: "ZP",
        iconColor: "#FB923C",
      },
      {
        userId: thomasId,
        merchant: "Poltu Quatu at Phi Beach Club",
        amount: "-123.64",
        currency: "AUD",
        originalAmount: "-68.00",
        originalCurrency: "EUR",
        category: "Food & Drink",
        status: "completed",
        description: "00:51 • -A$123.64",
        date: new Date("2024-07-21T00:51:00"),
        merchantIcon: "PQ",
        iconColor: "#FB923C",
      },
      {
        userId: thomasId,
        merchant: "Zuma Porto Cervo",
        amount: "-40.09",
        currency: "AUD",
        originalAmount: "-22.05",
        originalCurrency: "EUR",
        category: "Food & Drink",
        status: "completed",
        description: "00:44 • -A$40.09",
        date: new Date("2024-07-21T00:44:00"),
        merchantIcon: "ZP",
        iconColor: "#FB923C",
      },
      {
        userId: thomasId,
        merchant: "Zuma Porto Cervo",
        amount: "-123.64",
        currency: "AUD",
        originalAmount: "-68.00",
        originalCurrency: "EUR",
        category: "Food & Drink",
        status: "completed",
        description: "00:19 • -A$123.64",
        date: new Date("2024-07-21T00:19:00"),
        merchantIcon: "ZP",
        iconColor: "#FB923C",
      },
      {
        userId: thomasId,
        merchant: "Poltu Quatu at Phi Beach Club",
        amount: "-65.45",
        currency: "AUD",
        originalAmount: "-36.00",
        originalCurrency: "EUR",
        category: "Food & Drink",
        status: "completed",
        description: "00:17 • -A$65.45",
        date: new Date("2024-07-21T00:17:00"),
        merchantIcon: "PQ",
        iconColor: "#FB923C",
      },
      {
        userId: thomasId,
        merchant: "Zuma Porto Cervo",
        amount: "-450.89",
        currency: "AUD",
        originalAmount: "-247.99",
        originalCurrency: "EUR",
        category: "Food & Drink",
        status: "completed",
        description: "23:58 • -A$450.89",
        date: new Date("2024-07-20T23:58:00"),
        merchantIcon: "ZP",
        iconColor: "#FB923C",
      },
      {
        userId: thomasId,
        merchant: "Zuma Porto Cervo",
        amount: "-450.89",
        currency: "AUD",
        originalAmount: "-247.99",
        originalCurrency: "EUR",
        category: "Food & Drink",
        status: "completed",
        description: "23:58 • -A$450.89",
        date: new Date("2024-07-20T23:58:00"),
        merchantIcon: "ZP",
        iconColor: "#FB923C",
      },
      {
        userId: thomasId,
        merchant: "Zuma Porto Cervo",
        amount: "-323.64",
        currency: "AUD",
        originalAmount: "-178.00",
        originalCurrency: "EUR",
        category: "Food & Drink",
        status: "completed",
        description: "23:31 • -A$323.64",
        date: new Date("2024-07-20T23:31:00"),
        merchantIcon: "ZP",
        iconColor: "#FB923C",
      },
      {
        userId: thomasId,
        merchant: "Zuma Porto Cervo",
        amount: "-323.64",
        currency: "AUD",
        originalAmount: "-178.00",
        originalCurrency: "EUR",
        category: "Food & Drink",
        status: "completed",
        description: "23:31 • -A$323.64",
        date: new Date("2024-07-20T23:31:00"),
        merchantIcon: "ZP",
        iconColor: "#FB923C",
      },
      {
        userId: thomasId,
        merchant: "Zuma Porto Cervo",
        amount: "-29.09",
        currency: "AUD",
        originalAmount: "-16.00",
        originalCurrency: "EUR",
        category: "Food & Drink",
        status: "completed",
        description: "23:14 • -A$29.09",
        date: new Date("2024-07-20T23:14:00"),
        merchantIcon: "ZP",
        iconColor: "#FB923C",
      },
      {
        userId: thomasId,
        merchant: "Zuma Porto Cervo",
        amount: "-29.09",
        currency: "AUD",
        originalAmount: "-16.00",
        originalCurrency: "EUR",
        category: "Food & Drink",
        status: "completed",
        description: "23:14 • -A$29.09",
        date: new Date("2024-07-20T23:14:00"),
        merchantIcon: "ZP",
        iconColor: "#FB923C",
      },
      {
        userId: thomasId,
        merchant: "Zuma Porto Cervo",
        amount: "-123.64",
        currency: "AUD",
        originalAmount: "-68.00",
        originalCurrency: "EUR",
        category: "Food & Drink",
        status: "completed",
        description: "23:05 • -A$123.64",
        date: new Date("2024-07-20T23:05:00"),
        merchantIcon: "ZP",
        iconColor: "#FB923C",
      },
      {
        userId: thomasId,
        merchant: "Zuma Porto Cervo",
        amount: "-123.64",
        currency: "AUD",
        originalAmount: "-68.00",
        originalCurrency: "EUR",
        category: "Food & Drink",
        status: "completed",
        description: "23:05 • -A$123.64",
        date: new Date("2024-07-20T23:05:00"),
        merchantIcon: "ZP",
        iconColor: "#FB923C",
      },
      {
        userId: thomasId,
        merchant: "Zuma Porto Cervo",
        amount: "-40.09",
        currency: "AUD",
        originalAmount: "-22.05",
        originalCurrency: "EUR",
        category: "Food & Drink",
        status: "completed",
        description: "22:57 • -A$40.09",
        date: new Date("2024-07-20T22:57:00"),
        merchantIcon: "ZP",
        iconColor: "#FB923C",
      },
      {
        userId: thomasId,
        merchant: "Zuma Porto Cervo",
        amount: "-40.09",
        currency: "AUD",
        originalAmount: "-22.05",
        originalCurrency: "EUR",
        category: "Food & Drink",
        status: "completed",
        description: "22:57 • -A$40.09",
        date: new Date("2024-07-20T22:57:00"),
        merchantIcon: "ZP",
        iconColor: "#FB923C",
      },
      {
        userId: thomasId,
        merchant: "Zuma Porto Cervo",
        amount: "-123.64",
        currency: "AUD",
        originalAmount: "-68.00",
        originalCurrency: "EUR",
        category: "Food & Drink",
        status: "completed",
        description: "22:32 • -A$123.64",
        date: new Date("2024-07-20T22:32:00"),
        merchantIcon: "ZP",
        iconColor: "#FB923C",
      },
      {
        userId: thomasId,
        merchant: "Zuma Porto Cervo",
        amount: "-123.64",
        currency: "AUD",
        originalAmount: "-68.00",
        originalCurrency: "EUR",
        category: "Food & Drink",
        status: "completed",
        description: "22:32 • -A$123.64",
        date: new Date("2024-07-20T22:32:00"),
        merchantIcon: "ZP",
        iconColor: "#FB923C",
      },
      {
        userId: thomasId,
        merchant: "Zuma Porto Cervo",
        amount: "-29.09",
        currency: "AUD",
        originalAmount: "-16.00",
        originalCurrency: "EUR",
        category: "Food & Drink",
        status: "completed",
        description: "22:17 • -A$29.09",
        date: new Date("2024-07-20T22:17:00"),
        merchantIcon: "ZP",
        iconColor: "#FB923C",
      },
      {
        userId: thomasId,
        merchant: "Zuma Porto Cervo",
        amount: "-29.09",
        currency: "AUD",
        originalAmount: "-16.00",
        originalCurrency: "EUR",
        category: "Food & Drink",
        status: "completed",
        description: "22:17 • -A$29.09",
        date: new Date("2024-07-20T22:17:00"),
        merchantIcon: "ZP",
        iconColor: "#FB923C",
      },
      {
        userId: thomasId,
        merchant: "Zuma Porto Cervo",
        amount: "-123.64",
        currency: "AUD",
        originalAmount: "-68.00",
        originalCurrency: "EUR",
        category: "Food & Drink",
        status: "completed",
        description: "22:08 • -A$123.64",
        date: new Date("2024-07-20T22:08:00"),
        merchantIcon: "ZP",
        iconColor: "#FB923C",
      },
      {
        userId: thomasId,
        merchant: "Zuma Porto Cervo",
        amount: "-123.64",
        currency: "AUD",
        originalAmount: "-68.00",
        originalCurrency: "EUR",
        category: "Food & Drink",
        status: "completed",
        description: "22:08 • -A$123.64",
        date: new Date("2024-07-20T22:08:00"),
        merchantIcon: "ZP",
        iconColor: "#FB923C",
      },
      {
        userId: thomasId,
        merchant: "Uber Porto Cervo",
        amount: "-59.09",
        currency: "AUD",
        originalAmount: "-32.40",
        originalCurrency: "EUR",
        category: "Transport",
        status: "completed",
        description: "22:04 • -A$59.09",
        date: new Date("2024-07-20T22:04:00"),
        merchantIcon: "UP",
        iconColor: "#0066CC",
      },
      {
        userId: thomasId,
        merchant: "Novikov Porto Cervo",
        amount: "-563.64",
        currency: "AUD",
        originalAmount: "-310.00",
        originalCurrency: "EUR",
        category: "Food & Drink",
        status: "completed",
        description: "19:18 • -A$563.64",
        date: new Date("2024-07-20T19:18:00"),
        merchantIcon: "NP",
        iconColor: "#FB923C",
      },
      {
        userId: thomasId,
        merchant: "Sardinia Boat Charter",
        amount: "-1825.45",
        currency: "AUD",
        originalAmount: "-1004.00",
        originalCurrency: "EUR",
        category: "Entertainment",
        status: "completed",
        description: "16:12 • -A$1825.45",
        date: new Date("2024-07-20T16:12:00"),
        merchantIcon: "SB",
        iconColor: "#9333EA",
      },
      {
        userId: thomasId,
        merchant: "Charlie Faulkner",
        amount: "-300.00",
        currency: "AUD",
        originalAmount: null,
        originalCurrency: null,
        category: "Shopping",
        status: "completed",
        description: "Transfer • -A$300.00",
        date: new Date("2024-07-20T15:00:00"),
        merchantIcon: "CF",
        iconColor: "#DC2626",
      },
      {
        userId: thomasId,
        merchant: "Taxi Olbia → CBH Pevero",
        amount: "-161.82",
        currency: "AUD",
        originalAmount: "-89.00",
        originalCurrency: "EUR",
        category: "Transport",
        status: "completed",
        description: "14:06 • -A$161.82",
        date: new Date("2024-07-20T14:06:00"),
        merchantIcon: "TO",
        iconColor: "#0066CC",
      },
      {
        userId: thomasId,
        merchant: "Booking.com",
        amount: "-4454.55",
        currency: "AUD",
        originalAmount: "-2450.00",
        originalCurrency: "EUR",
        category: "Accommodation",
        status: "completed",
        description: "13:09 • -A$4454.55",
        date: new Date("2024-07-20T13:09:00"),
        merchantIcon: "BO",
        iconColor: "#A855F7",
      },
      {
        userId: thomasId,
        merchant: "Zuma Porto Cervo",
        amount: "-123.64",
        currency: "AUD",
        originalAmount: "-68.00",
        originalCurrency: "EUR",
        category: "Food & Drink",
        status: "completed",
        description: "01:58 • -A$123.64",
        date: new Date("2024-07-20T01:58:00"),
        merchantIcon: "ZP",
        iconColor: "#FB923C",
      },
      {
        userId: thomasId,
        merchant: "Zuma Porto Cervo",
        amount: "-29.09",
        currency: "AUD",
        originalAmount: "-16.00",
        originalCurrency: "EUR",
        category: "Food & Drink",
        status: "completed",
        description: "01:41 • -A$29.09",
        date: new Date("2024-07-20T01:41:00"),
        merchantIcon: "ZP",
        iconColor: "#FB923C",
      },
      {
        userId: thomasId,
        merchant: "Zuma Porto Cervo",
        amount: "-123.64",
        currency: "AUD",
        originalAmount: "-68.00",
        originalCurrency: "EUR",
        category: "Food & Drink",
        status: "completed",
        description: "01:27 • -A$123.64",
        date: new Date("2024-07-20T01:27:00"),
        merchantIcon: "ZP",
        iconColor: "#FB923C",
      },
      {
        userId: thomasId,
        merchant: "Zuma Porto Cervo",
        amount: "-234.55",
        currency: "AUD",
        originalAmount: "-129.00",
        originalCurrency: "EUR",
        category: "Food & Drink",
        status: "completed",
        description: "01:06 • -A$234.55",
        date: new Date("2024-07-20T01:06:00"),
        merchantIcon: "ZP",
        iconColor: "#FB923C",
      },
      {
        userId: thomasId,
        merchant: "Zuma Porto Cervo",
        amount: "-40.09",
        currency: "AUD",
        originalAmount: "-22.05",
        originalCurrency: "EUR",
        category: "Food & Drink",
        status: "completed",
        description: "00:44 • -A$40.09",
        date: new Date("2024-07-20T00:44:00"),
        merchantIcon: "ZP",
        iconColor: "#FB923C",
      },
      {
        userId: thomasId,
        merchant: "Zuma Porto Cervo",
        amount: "-123.64",
        currency: "AUD",
        originalAmount: "-68.00",
        originalCurrency: "EUR",
        category: "Food & Drink",
        status: "completed",
        description: "00:19 • -A$123.64",
        date: new Date("2024-07-20T00:19:00"),
        merchantIcon: "ZP",
        iconColor: "#FB923C",
      },
      {
        userId: thomasId,
        merchant: "Uber Napoli",
        amount: "-35.64",
        currency: "AUD",
        originalAmount: "-19.60",
        originalCurrency: "EUR",
        category: "Transport",
        status: "completed",
        description: "18:39 • -A$35.64",
        date: new Date("2024-07-19T18:39:00"),
        merchantIcon: "UN",
        iconColor: "#0066CC",
      },
      {
        userId: thomasId,
        merchant: "Taxi Napoli Port → Aeroporto",
        amount: "-69.09",
        currency: "AUD",
        originalAmount: "-38.00",
        originalCurrency: "EUR",
        category: "Transport",
        status: "completed",
        description: "12:02 • -A$69.09",
        date: new Date("2024-07-19T12:02:00"),
        merchantIcon: "TN",
        iconColor: "#0066CC",
      },
      {
        userId: thomasId,
        merchant: "Booking.com",
        amount: "-287.27",
        currency: "AUD",
        originalAmount: "-158.00",
        originalCurrency: "EUR",
        category: "Accommodation",
        status: "completed",
        description: "09:55 • -A$287.27",
        date: new Date("2024-07-19T09:55:00"),
        merchantIcon: "BO",
        iconColor: "#A855F7",
      },
      {
        userId: thomasId,
        merchant: "Al Palazzo",
        amount: "-450.91",
        currency: "AUD",
        originalAmount: "-248.00",
        originalCurrency: "EUR",
        category: "Food & Drink",
        status: "completed",
        description: "20:14 • -A$450.91",
        date: new Date("2024-07-18T20:14:00"),
        merchantIcon: "AP",
        iconColor: "#FB923C",
      },
      {
        userId: thomasId,
        merchant: "MR PORTER",
        amount: "-458.33",
        currency: "AUD",
        originalAmount: "-220.00",
        originalCurrency: "GBP",
        category: "Shopping",
        status: "completed",
        description: "Online • -A$458.33",
        date: new Date("2024-07-18T14:00:00"),
        merchantIcon: "MR",
        iconColor: "#DC2626",
      },
      {
        userId: thomasId,
        merchant: "Arienzo Beach Club",
        amount: "-138.18",
        currency: "AUD",
        originalAmount: "-76.00",
        originalCurrency: "EUR",
        category: "Food & Drink",
        status: "completed",
        description: "12:26 • -A$138.18",
        date: new Date("2024-07-18T12:26:00"),
        merchantIcon: "AB",
        iconColor: "#FB923C",
      },
      {
        userId: thomasId,
        merchant: "Bar Pasticceria Collina",
        amount: "-40.00",
        currency: "AUD",
        originalAmount: "-22.00",
        originalCurrency: "EUR",
        category: "Food & Drink",
        status: "completed",
        description: "09:12 • -A$40.00",
        date: new Date("2024-07-18T09:12:00"),
        merchantIcon: "BP",
        iconColor: "#FB923C",
      },
      {
        userId: thomasId,
        merchant: "La Sponda",
        amount: "-723.64",
        currency: "AUD",
        originalAmount: "-398.00",
        originalCurrency: "EUR",
        category: "Food & Drink",
        status: "completed",
        description: "20:07 • -A$723.64",
        date: new Date("2024-07-17T20:07:00"),
        merchantIcon: "LS",
        iconColor: "#FB923C",
      },
      {
        userId: thomasId,
        merchant: "Booking.com",
        amount: "-5167.27",
        currency: "AUD",
        originalAmount: "-2842.00",
        originalCurrency: "EUR",
        category: "Accommodation",
        status: "completed",
        description: "12:18 • -A$5167.27",
        date: new Date("2024-07-17T12:18:00"),
        merchantIcon: "BO",
        iconColor: "#A855F7",
      },
      {
        userId: thomasId,
        merchant: "Alilauro Hydrofoil",
        amount: "-105.45",
        currency: "AUD",
        originalAmount: "-58.00",
        originalCurrency: "EUR",
        category: "Transport",
        status: "completed",
        description: "10:42 • -A$105.45",
        date: new Date("2024-07-17T10:42:00"),
        merchantIcon: "AH",
        iconColor: "#0066CC",
      },
      {
        userId: thomasId,
        merchant: "Ristorante Il Buco",
        amount: "-381.82",
        currency: "AUD",
        originalAmount: "-210.00",
        originalCurrency: "EUR",
        category: "Food & Drink",
        status: "completed",
        description: "20:19 • -A$381.82",
        date: new Date("2024-07-16T20:19:00"),
        merchantIcon: "RI",
        iconColor: "#FB923C",
      },
      {
        userId: thomasId,
        merchant: "Fauno Bar",
        amount: "-81.82",
        currency: "AUD",
        originalAmount: "-45.00",
        originalCurrency: "EUR",
        category: "Food & Drink",
        status: "completed",
        description: "13:02 • -A$81.82",
        date: new Date("2024-07-16T13:02:00"),
        merchantIcon: "FB",
        iconColor: "#FB923C",
      },
      {
        userId: thomasId,
        merchant: "Taxi Sorrento",
        amount: "-109.09",
        currency: "AUD",
        originalAmount: "-60.00",
        originalCurrency: "EUR",
        category: "Transport",
        status: "completed",
        description: "11:34 • -A$109.09",
        date: new Date("2024-07-16T11:34:00"),
        merchantIcon: "TS",
        iconColor: "#0066CC",
      },
      {
        userId: thomasId,
        merchant: "Pasticceria Primavera",
        amount: "-25.45",
        currency: "AUD",
        originalAmount: "-14.00",
        originalCurrency: "EUR",
        category: "Food & Drink",
        status: "completed",
        description: "09:06 • -A$25.45",
        date: new Date("2024-07-16T09:06:00"),
        merchantIcon: "PP",
        iconColor: "#FB923C",
      },
      {
        userId: thomasId,
        merchant: "Bar Sorrento",
        amount: "-17.82",
        currency: "AUD",
        originalAmount: "-9.80",
        originalCurrency: "EUR",
        category: "Food & Drink",
        status: "completed",
        description: "18:41 • -A$17.82",
        date: new Date("2024-07-15T18:41:00"),
        merchantIcon: "BS",
        iconColor: "#FB923C",
      },
      {
        userId: thomasId,
        merchant: "Suisse Pompei",
        amount: "-12.91",
        currency: "AUD",
        originalAmount: "-7.10",
        originalCurrency: "EUR",
        category: "Food & Drink",
        status: "completed",
        description: "15:12 • -A$12.91",
        date: new Date("2024-07-15T15:12:00"),
        merchantIcon: "SP",
        iconColor: "#FB923C",
      },
      {
        userId: thomasId,
        merchant: "Suisse Pompei",
        amount: "-33.09",
        currency: "AUD",
        originalAmount: "-18.20",
        originalCurrency: "EUR",
        category: "Food & Drink",
        status: "completed",
        description: "13:04 • -A$33.09",
        date: new Date("2024-07-15T13:04:00"),
        merchantIcon: "SP",
        iconColor: "#FB923C",
      },
      {
        userId: thomasId,
        merchant: "Farfetch",
        amount: "-302.08",
        currency: "AUD",
        originalAmount: "-145.00",
        originalCurrency: "GBP",
        category: "Shopping",
        status: "completed",
        description: "Online • -A$302.08",
        date: new Date("2024-07-15T12:00:00"),
        merchantIcon: "FA",
        iconColor: "#DC2626",
      },
      {
        userId: thomasId,
        merchant: "Bookshop Pompei Op. La",
        amount: "-13.64",
        currency: "AUD",
        originalAmount: "-7.50",
        originalCurrency: "EUR",
        category: "Entertainment",
        status: "completed",
        description: "11:21 • -A$13.64",
        date: new Date("2024-07-15T11:21:00"),
        merchantIcon: "BP",
        iconColor: "#9333EA",
      },
      {
        userId: thomasId,
        merchant: "Parco Archeologico di Pompei",
        amount: "-54.55",
        currency: "AUD",
        originalAmount: "-30.00",
        originalCurrency: "EUR",
        category: "Entertainment",
        status: "completed",
        description: "09:58 • -A$54.55",
        date: new Date("2024-07-15T09:58:00"),
        merchantIcon: "PA",
        iconColor: "#9333EA",
      },
      {
        userId: thomasId,
        merchant: "Trattoria Sorrento",
        amount: "-112.73",
        currency: "AUD",
        originalAmount: "-62.00",
        originalCurrency: "EUR",
        category: "Food & Drink",
        status: "completed",
        description: "19:26 • -A$112.73",
        date: new Date("2024-07-14T19:26:00"),
        merchantIcon: "TS",
        iconColor: "#FB923C",
      },
      {
        userId: thomasId,
        merchant: "Bar Napoli Centrale",
        amount: "-7.64",
        currency: "AUD",
        originalAmount: "-4.20",
        originalCurrency: "EUR",
        category: "Food & Drink",
        status: "completed",
        description: "13:17 • -A$7.64",
        date: new Date("2024-07-14T13:17:00"),
        merchantIcon: "BN",
        iconColor: "#FB923C",
      },
      {
        userId: thomasId,
        merchant: "Agoda",
        amount: "-763.64",
        currency: "AUD",
        originalAmount: "-420.00",
        originalCurrency: "EUR",
        category: "Accommodation",
        status: "completed",
        description: "12:08 • -A$763.64",
        date: new Date("2024-07-14T12:08:00"),
        merchantIcon: "AG",
        iconColor: "#A855F7",
      },
      {
        userId: thomasId,
        merchant: "Consorzio Taxi Napoli",
        amount: "-172.73",
        currency: "AUD",
        originalAmount: "-95.00",
        originalCurrency: "EUR",
        category: "Transport",
        status: "completed",
        description: "10:41 • -A$172.73",
        date: new Date("2024-07-14T10:41:00"),
        merchantIcon: "CT",
        iconColor: "#0066CC",
      },
      {
        userId: thomasId,
        merchant: "Trenitalia",
        amount: "-87.27",
        currency: "AUD",
        originalAmount: "-48.00",
        originalCurrency: "EUR",
        category: "Transport",
        status: "completed",
        description: "09:02 • -A$87.27",
        date: new Date("2024-07-14T09:02:00"),
        merchantIcon: "TR",
        iconColor: "#0066CC",
      },
      {
        userId: thomasId,
        merchant: "Uber Roma",
        amount: "-32.73",
        currency: "AUD",
        originalAmount: "-18.00",
        originalCurrency: "EUR",
        category: "Transport",
        status: "completed",
        description: "22:43 • -A$32.73",
        date: new Date("2024-07-13T22:43:00"),
        merchantIcon: "UR",
        iconColor: "#0066CC",
      },
      {
        userId: thomasId,
        merchant: "Aroma Restaurant",
        amount: "-381.82",
        currency: "AUD",
        originalAmount: "-210.00",
        originalCurrency: "EUR",
        category: "Food & Drink",
        status: "completed",
        description: "20:11 • -A$381.82",
        date: new Date("2024-07-13T20:11:00"),
        merchantIcon: "AR",
        iconColor: "#FB923C",
      },
      {
        userId: thomasId,
        merchant: "Agoda",
        amount: "-581.82",
        currency: "AUD",
        originalAmount: "-320.00",
        originalCurrency: "EUR",
        category: "Accommodation",
        status: "completed",
        description: "18:22 • -A$581.82",
        date: new Date("2024-07-13T18:22:00"),
        merchantIcon: "AG",
        iconColor: "#A855F7",
      },
      {
        userId: thomasId,
        merchant: "Caffè Sant'Eustachio",
        amount: "-13.64",
        currency: "AUD",
        originalAmount: "-7.50",
        originalCurrency: "EUR",
        category: "Shopping",
        status: "completed",
        description: "14:31 • -A$13.64",
        date: new Date("2024-07-13T14:31:00"),
        merchantIcon: "CS",
        iconColor: "#DC2626",
      },
      {
        userId: thomasId,
        merchant: "Trattoria Luzzi",
        amount: "-50.91",
        currency: "AUD",
        originalAmount: "-28.00",
        originalCurrency: "EUR",
        category: "Food & Drink",
        status: "completed",
        description: "12:19 • -A$50.91",
        date: new Date("2024-07-13T12:19:00"),
        merchantIcon: "TL",
        iconColor: "#FB923C",
      },
      {
        userId: thomasId,
        merchant: "CoopCulture Roma",
        amount: "-72.73",
        currency: "AUD",
        originalAmount: "-40.00",
        originalCurrency: "EUR",
        category: "Shopping",
        status: "completed",
        description: "10:06 • -A$72.73",
        date: new Date("2024-07-13T10:06:00"),
        merchantIcon: "CR",
        iconColor: "#DC2626",
      },
      {
        userId: thomasId,
        merchant: "Street Food Roma",
        amount: "-13.09",
        currency: "AUD",
        originalAmount: "-7.20",
        originalCurrency: "EUR",
        category: "Food & Drink",
        status: "completed",
        description: "18:36 • -A$13.09",
        date: new Date("2024-07-12T18:36:00"),
        merchantIcon: "SF",
        iconColor: "#FB923C",
      },
      {
        userId: thomasId,
        merchant: "Carrefour Express Roma",
        amount: "-7.45",
        currency: "AUD",
        originalAmount: "-4.10",
        originalCurrency: "EUR",
        category: "Food & Drink",
        status: "completed",
        description: "15:02 • -A$7.45",
        date: new Date("2024-07-12T15:02:00"),
        merchantIcon: "CE",
        iconColor: "#FB923C",
      },
      {
        userId: thomasId,
        merchant: "Taxi Roma FCO",
        amount: "-94.55",
        currency: "AUD",
        originalAmount: "-52.00",
        originalCurrency: "EUR",
        category: "Transport",
        status: "completed",
        description: "13:16 • -A$94.55",
        date: new Date("2024-07-12T13:16:00"),
        merchantIcon: "TR",
        iconColor: "#0066CC",
      },
      {
        userId: thomasId,
        merchant: "Ryanair Inflight",
        amount: "-5.45",
        currency: "AUD",
        originalAmount: "-3.00",
        originalCurrency: "EUR",
        category: "Transport",
        status: "completed",
        description: "12:02 • -A$5.45",
        date: new Date("2024-07-12T12:02:00"),
        merchantIcon: "RI",
        iconColor: "#0066CC",
      },
      {
        userId: thomasId,
        merchant: "Ryanair Late Check-In",
        amount: "-114.58",
        currency: "AUD",
        originalAmount: "-55.00",
        originalCurrency: "GBP",
        category: "Transport",
        status: "completed",
        description: "09:54 • -A$114.58",
        date: new Date("2024-07-12T09:54:00"),
        merchantIcon: "RL",
        iconColor: "#0066CC",
      },
      {
        userId: thomasId,
        merchant: "Transport for London",
        amount: "-11.67",
        currency: "AUD",
        originalAmount: "-5.60",
        originalCurrency: "GBP",
        category: "Transport",
        status: "completed",
        description: "08:11 • -A$11.67",
        date: new Date("2024-07-12T08:11:00"),
        merchantIcon: "TFL",
        iconColor: "#0066CC",
      },
      {
        userId: thomasId,
        merchant: "South Western Railway",
        amount: "-82.50",
        currency: "AUD",
        originalAmount: "-39.60",
        originalCurrency: "GBP",
        category: "Transport",
        status: "completed",
        description: "07:08 • -A$82.50",
        date: new Date("2024-07-12T07:08:00"),
        merchantIcon: "SW",
        iconColor: "#0066CC",
      },
      {
        userId: thomasId,
        merchant: "Ryanair",
        amount: "-141.67",
        currency: "AUD",
        originalAmount: "-68.00",
        originalCurrency: "GBP",
        category: "Transport",
        status: "completed",
        description: "18:21 • -A$141.67",
        date: new Date("2024-07-11T18:21:00"),
        merchantIcon: "RY",
        iconColor: "#0066CC",
      },
      {
        userId: thomasId,
        merchant: "Agoda",
        amount: "-1636.36",
        currency: "AUD",
        originalAmount: "-900.00",
        originalCurrency: "EUR",
        category: "Accommodation",
        status: "completed",
        description: "12:58 • -A$1636.36",
        date: new Date("2024-07-11T12:58:00"),
        merchantIcon: "AG",
        iconColor: "#A855F7",
      },
      {
        userId: thomasId,
        merchant: "Leckford Farm Shop Café",
        amount: "-25.83",
        currency: "AUD",
        originalAmount: "-12.40",
        originalCurrency: "GBP",
        category: "Shopping",
        status: "completed",
        description: "10:36 • -A$25.83",
        date: new Date("2024-07-11T10:36:00"),
        merchantIcon: "LF",
        iconColor: "#DC2626",
      },
      {
        userId: thomasId,
        merchant: "Sainsbury's Local Winchester",
        amount: "-12.71",
        currency: "AUD",
        originalAmount: "-6.10",
        originalCurrency: "GBP",
        category: "Food & Drink",
        status: "completed",
        description: "16:22 • -A$12.71",
        date: new Date("2024-07-10T16:22:00"),
        merchantIcon: "SL",
        iconColor: "#FB923C",
      },
      {
        userId: thomasId,
        merchant: "Flat Whites Winchester",
        amount: "-16.25",
        currency: "AUD",
        originalAmount: "-7.80",
        originalCurrency: "GBP",
        category: "Shopping",
        status: "completed",
        description: "09:48 • -A$16.25",
        date: new Date("2024-07-10T09:48:00"),
        merchantIcon: "FW",
        iconColor: "#DC2626",
      },
      {
        userId: thomasId,
        merchant: "WHSmith Heathrow T2",
        amount: "-52.06",
        currency: "AUD",
        originalAmount: "-24.99",
        originalCurrency: "GBP",
        category: "Shopping",
        status: "completed",
        description: "15:05 • -A$52.06",
        date: new Date("2024-07-09T15:05:00"),
        merchantIcon: "WH",
        iconColor: "#DC2626",
      },
      {
        userId: thomasId,
        merchant: "Transport for London",
        amount: "-14.38",
        currency: "AUD",
        originalAmount: "-6.90",
        originalCurrency: "GBP",
        category: "Transport",
        status: "completed",
        description: "13:17 • -A$14.38",
        date: new Date("2024-07-09T13:17:00"),
        merchantIcon: "TFL",
        iconColor: "#0066CC",
      },
      {
        userId: thomasId,
        merchant: "BP Express Finchley Road",
        amount: "-95.42",
        currency: "AUD",
        originalAmount: "-45.80",
        originalCurrency: "GBP",
        category: "Shopping",
        status: "completed",
        description: "11:22 • -A$95.42",
        date: new Date("2024-07-09T11:22:00"),
        merchantIcon: "BE",
        iconColor: "#DC2626",
      },
      {
        userId: thomasId,
        merchant: "Gail's Bakery Hampstead",
        amount: "-19.58",
        currency: "AUD",
        originalAmount: "-9.40",
        originalCurrency: "GBP",
        category: "Food & Drink",
        status: "completed",
        description: "08:05 • -A$19.58",
        date: new Date("2024-07-09T08:05:00"),
        merchantIcon: "GB",
        iconColor: "#FB923C",
      },
      {
        userId: thomasId,
        merchant: "Tinder",
        amount: "-27.06",
        currency: "AUD",
        originalAmount: "-12.99",
        originalCurrency: "GBP",
        category: "Technology",
        status: "completed",
        description: "20:33 • -A$27.06",
        date: new Date("2024-07-08T20:33:00"),
        merchantIcon: "TI",
        iconColor: "#000000",
      },
      {
        userId: thomasId,
        merchant: "Tinder",
        amount: "-27.06",
        currency: "AUD",
        originalAmount: "-12.99",
        originalCurrency: "GBP",
        category: "Technology",
        status: "completed",
        description: "20:33 • -A$27.06",
        date: new Date("2024-07-08T20:33:00"),
        merchantIcon: "TI",
        iconColor: "#000000",
      },
      {
        userId: thomasId,
        merchant: "Apple.com/billing",
        amount: "-7.27",
        currency: "AUD",
        originalAmount: "-3.49",
        originalCurrency: "GBP",
        category: "Technology",
        status: "completed",
        description: "14:42 • -A$7.27",
        date: new Date("2024-07-08T14:42:00"),
        merchantIcon: "apple",
        iconColor: "#000000",
      },
      {
        userId: thomasId,
        merchant: "Apple.com/billing",
        amount: "-7.27",
        currency: "AUD",
        originalAmount: "-3.49",
        originalCurrency: "GBP",
        category: "Technology",
        status: "completed",
        description: "14:42 • -A$7.27",
        date: new Date("2024-07-08T14:42:00"),
        merchantIcon: "AP",
        iconColor: "#000000",
      },
      {
        userId: thomasId,
        merchant: "Gail's Bakery Hampstead",
        amount: "-16.88",
        currency: "AUD",
        originalAmount: "-8.10",
        originalCurrency: "GBP",
        category: "Food & Drink",
        status: "completed",
        description: "09:21 • -A$16.88",
        date: new Date("2024-07-08T09:21:00"),
        merchantIcon: "GB",
        iconColor: "#FB923C",
      },
      {
        userId: thomasId,
        merchant: "Hinge",
        amount: "-41.65",
        currency: "AUD",
        originalAmount: "-19.99",
        originalCurrency: "GBP",
        category: "Technology",
        status: "completed",
        description: "23:11 • -A$41.65",
        date: new Date("2024-07-07T23:11:00"),
        merchantIcon: "HI",
        iconColor: "#000000",
      },
      {
        userId: thomasId,
        merchant: "Hinge",
        amount: "-41.65",
        currency: "AUD",
        originalAmount: "-19.99",
        originalCurrency: "GBP",
        category: "Technology",
        status: "completed",
        description: "23:11 • -A$41.65",
        date: new Date("2024-07-07T23:11:00"),
        merchantIcon: "HI",
        iconColor: "#000000",
      },
      {
        userId: thomasId,
        merchant: "Uber London",
        amount: "-38.13",
        currency: "AUD",
        originalAmount: "-18.30",
        originalCurrency: "GBP",
        category: "Transport",
        status: "completed",
        description: "21:07 • -A$38.13",
        date: new Date("2024-07-07T21:07:00"),
        merchantIcon: "UL",
        iconColor: "#0066CC",
      },
      {
        userId: thomasId,
        merchant: "The Stag Belsize Park",
        amount: "-85.83",
        currency: "AUD",
        originalAmount: "-41.20",
        originalCurrency: "GBP",
        category: "Food & Drink",
        status: "completed",
        description: "18:49 • -A$85.83",
        date: new Date("2024-07-07T18:49:00"),
        merchantIcon: "TS",
        iconColor: "#FB923C",
      },
      {
        userId: thomasId,
        merchant: "Costa Coffee Camden Town",
        amount: "-7.29",
        currency: "AUD",
        originalAmount: "-3.50",
        originalCurrency: "GBP",
        category: "Food & Drink",
        status: "completed",
        description: "15:22 • -A$7.29",
        date: new Date("2024-07-07T15:22:00"),
        merchantIcon: "CC",
        iconColor: "#FB923C",
      },
      {
        userId: thomasId,
        merchant: "Pret A Manger Camden High St",
        amount: "-13.96",
        currency: "AUD",
        originalAmount: "-6.70",
        originalCurrency: "GBP",
        category: "Food & Drink",
        status: "completed",
        description: "13:58 • -A$13.96",
        date: new Date("2024-07-07T13:58:00"),
        merchantIcon: "PA",
        iconColor: "#FB923C",
      },
      {
        userId: thomasId,
        merchant: "Dr. Martens Camden",
        amount: "-200.00",
        currency: "AUD",
        originalAmount: "-96.00",
        originalCurrency: "GBP",
        category: "Shopping",
        status: "completed",
        description: "12:15 • -A$200.00",
        date: new Date("2024-07-07T12:15:00"),
        merchantIcon: "DM",
        iconColor: "#DC2626",
      },
      {
        userId: thomasId,
        merchant: "Camden Market",
        amount: "-23.75",
        currency: "AUD",
        originalAmount: "-11.40",
        originalCurrency: "GBP",
        category: "Shopping",
        status: "completed",
        description: "11:32 • -A$23.75",
        date: new Date("2024-07-07T11:32:00"),
        merchantIcon: "CM",
        iconColor: "#DC2626",
      },
      {
        userId: thomasId,
        merchant: "Transport for London",
        amount: "-10.21",
        currency: "AUD",
        originalAmount: "-4.90",
        originalCurrency: "GBP",
        category: "Transport",
        status: "completed",
        description: "11:04 • -A$10.21",
        date: new Date("2024-07-07T11:04:00"),
        merchantIcon: "TFL",
        iconColor: "#0066CC",
      },
      {
        userId: thomasId,
        merchant: "Gail's Bakery Hampstead",
        amount: "-17.92",
        currency: "AUD",
        originalAmount: "-8.60",
        originalCurrency: "GBP",
        category: "Food & Drink",
        status: "completed",
        description: "08:33 • -A$17.92",
        date: new Date("2024-07-07T08:33:00"),
        merchantIcon: "GB",
        iconColor: "#FB923C",
      },
      {
        userId: thomasId,
        merchant: "The Stag Belsize Park",
        amount: "-82.50",
        currency: "AUD",
        originalAmount: "-39.60",
        originalCurrency: "GBP",
        category: "Food & Drink",
        status: "completed",
        description: "19:36 • -A$82.50",
        date: new Date("2024-07-06T19:36:00"),
        merchantIcon: "TS",
        iconColor: "#FB923C",
      },
      {
        userId: thomasId,
        merchant: "Transport for London",
        amount: "-6.67",
        currency: "AUD",
        originalAmount: "-3.20",
        originalCurrency: "GBP",
        category: "Transport",
        status: "completed",
        description: "16:45 • -A$6.67",
        date: new Date("2024-07-06T16:45:00"),
        merchantIcon: "TFL",
        iconColor: "#0066CC",
      },
      {
        userId: thomasId,
        merchant: "Starbucks Victoria Station",
        amount: "-7.92",
        currency: "AUD",
        originalAmount: "-3.80",
        originalCurrency: "GBP",
        category: "Food & Drink",
        status: "completed",
        description: "16:12 • -A$7.92",
        date: new Date("2024-07-06T16:12:00"),
        merchantIcon: "SV",
        iconColor: "#FB923C",
      },
      {
        userId: thomasId,
        merchant: "Buckingham Palace Tickets",
        amount: "-66.67",
        currency: "AUD",
        originalAmount: "-32.00",
        originalCurrency: "GBP",
        category: "Entertainment",
        status: "completed",
        description: "13:58 • -A$66.67",
        date: new Date("2024-07-06T13:58:00"),
        merchantIcon: "BP",
        iconColor: "#9333EA",
      },
      {
        userId: thomasId,
        merchant: "McDonald's Oxford Street",
        amount: "-16.46",
        currency: "AUD",
        originalAmount: "-7.90",
        originalCurrency: "GBP",
        category: "Shopping",
        status: "completed",
        description: "12:25 • -A$16.46",
        date: new Date("2024-07-06T12:25:00"),
        merchantIcon: "MO",
        iconColor: "#DC2626",
      },
      {
        userId: thomasId,
        merchant: "Costa Coffee Oxford Street",
        amount: "-8.54",
        currency: "AUD",
        originalAmount: "-4.10",
        originalCurrency: "GBP",
        category: "Food & Drink",
        status: "completed",
        description: "11:08 • -A$8.54",
        date: new Date("2024-07-06T11:08:00"),
        merchantIcon: "CC",
        iconColor: "#FB923C",
      },
      {
        userId: thomasId,
        merchant: "Transport for London",
        amount: "-6.67",
        currency: "AUD",
        originalAmount: "-3.20",
        originalCurrency: "GBP",
        category: "Transport",
        status: "completed",
        description: "09:52 • -A$6.67",
        date: new Date("2024-07-06T09:52:00"),
        merchantIcon: "TFL",
        iconColor: "#0066CC",
      },
      {
        userId: thomasId,
        merchant: "Gail's Bakery Hampstead",
        amount: "-19.17",
        currency: "AUD",
        originalAmount: "-9.20",
        originalCurrency: "GBP",
        category: "Food & Drink",
        status: "completed",
        description: "08:26 • -A$19.17",
        date: new Date("2024-07-06T08:26:00"),
        merchantIcon: "GB",
        iconColor: "#FB923C",
      },
      {
        userId: thomasId,
        merchant: "Uber London",
        amount: "-34.17",
        currency: "AUD",
        originalAmount: "-16.40",
        originalCurrency: "GBP",
        category: "Transport",
        status: "completed",
        description: "22:12 • -A$34.17",
        date: new Date("2024-07-05T22:12:00"),
        merchantIcon: "UL",
        iconColor: "#0066CC",
      },
      {
        userId: thomasId,
        merchant: "Waitrose Finchley Road",
        amount: "-54.79",
        currency: "AUD",
        originalAmount: "-26.30",
        originalCurrency: "GBP",
        category: "Food & Drink",
        status: "completed",
        description: "20:42 • -A$54.79",
        date: new Date("2024-07-05T20:42:00"),
        merchantIcon: "WF",
        iconColor: "#FB923C",
      },
      {
        userId: thomasId,
        merchant: "Gail's Bakery Hampstead",
        amount: "-16.25",
        currency: "AUD",
        originalAmount: "-7.80",
        originalCurrency: "GBP",
        category: "Food & Drink",
        status: "completed",
        description: "18:14 • -A$16.25",
        date: new Date("2024-07-05T18:14:00"),
        merchantIcon: "GB",
        iconColor: "#FB923C",
      },
      {
        userId: thomasId,
        merchant: "Lowry's Bar Clifden",
        amount: "-23.27",
        currency: "AUD",
        originalAmount: "-12.80",
        originalCurrency: "EUR",
        category: "Food & Drink",
        status: "completed",
        description: "17:48 • -A$23.27",
        date: new Date("2024-07-04T17:48:00"),
        merchantIcon: "LB",
        iconColor: "#FB923C",
      },
      {
        userId: thomasId,
        merchant: "Lowry's Bar Clifden",
        amount: "-61.27",
        currency: "AUD",
        originalAmount: "-33.70",
        originalCurrency: "EUR",
        category: "Food & Drink",
        status: "completed",
        description: "17:12 • -A$61.27",
        date: new Date("2024-07-04T17:12:00"),
        merchantIcon: "LB",
        iconColor: "#FB923C",
      },
      {
        userId: thomasId,
        merchant: "Tea House by the Walled Garden",
        amount: "-26.91",
        currency: "AUD",
        originalAmount: "-14.80",
        originalCurrency: "EUR",
        category: "Food & Drink",
        status: "completed",
        description: "14:03 • -A$26.91",
        date: new Date("2024-07-04T14:03:00"),
        merchantIcon: "TH",
        iconColor: "#FB923C",
      },
      {
        userId: thomasId,
        merchant: "Kylemore Café",
        amount: "-38.18",
        currency: "AUD",
        originalAmount: "-21.00",
        originalCurrency: "EUR",
        category: "Food & Drink",
        status: "completed",
        description: "12:37 • -A$38.18",
        date: new Date("2024-07-04T12:37:00"),
        merchantIcon: "KC",
        iconColor: "#FB923C",
      },
      {
        userId: thomasId,
        merchant: "Kylemore Abbey",
        amount: "-50.91",
        currency: "AUD",
        originalAmount: "-28.00",
        originalCurrency: "EUR",
        category: "Entertainment",
        status: "completed",
        description: "11:22 • -A$50.91",
        date: new Date("2024-07-04T11:22:00"),
        merchantIcon: "KA",
        iconColor: "#9333EA",
      },
      {
        userId: thomasId,
        merchant: "Circle K Athlone",
        amount: "-116.73",
        currency: "AUD",
        originalAmount: "-64.20",
        originalCurrency: "EUR",
        category: "Transport",
        status: "completed",
        description: "08:44 • -A$116.73",
        date: new Date("2024-07-04T08:44:00"),
        merchantIcon: "CK",
        iconColor: "#0066CC",
      },
      {
        userId: thomasId,
        merchant: "O'Donoghue's",
        amount: "-26.18",
        currency: "AUD",
        originalAmount: "-14.40",
        originalCurrency: "EUR",
        category: "Food & Drink",
        status: "completed",
        description: "22:32 • -A$26.18",
        date: new Date("2024-07-03T22:32:00"),
        merchantIcon: "O'",
        iconColor: "#FB923C",
      },
      {
        userId: thomasId,
        merchant: "O'Donoghue's",
        amount: "-32.00",
        currency: "AUD",
        originalAmount: "-17.60",
        originalCurrency: "EUR",
        category: "Food & Drink",
        status: "completed",
        description: "21:49 • -A$32.00",
        date: new Date("2024-07-03T21:49:00"),
        merchantIcon: "O'",
        iconColor: "#FB923C",
      },
      {
        userId: thomasId,
        merchant: "O'Donoghue's",
        amount: "-20.36",
        currency: "AUD",
        originalAmount: "-11.20",
        originalCurrency: "EUR",
        category: "Food & Drink",
        status: "completed",
        description: "21:06 • -A$20.36",
        date: new Date("2024-07-03T21:06:00"),
        merchantIcon: "O'",
        iconColor: "#FB923C",
      },
      {
        userId: thomasId,
        merchant: "O'Donoghue's",
        amount: "-40.00",
        currency: "AUD",
        originalAmount: "-22.00",
        originalCurrency: "EUR",
        category: "Food & Drink",
        status: "completed",
        description: "20:31 • -A$40.00",
        date: new Date("2024-07-03T20:31:00"),
        merchantIcon: "O'",
        iconColor: "#FB923C",
      },
      {
        userId: thomasId,
        merchant: "Grogan's Castle Lounge",
        amount: "-33.09",
        currency: "AUD",
        originalAmount: "-18.20",
        originalCurrency: "EUR",
        category: "Food & Drink",
        status: "completed",
        description: "14:48 • -A$33.09",
        date: new Date("2024-07-03T14:48:00"),
        merchantIcon: "GC",
        iconColor: "#FB923C",
      },
      {
        userId: thomasId,
        merchant: "Grogan's Castle Lounge",
        amount: "-17.45",
        currency: "AUD",
        originalAmount: "-9.60",
        originalCurrency: "EUR",
        category: "Food & Drink",
        status: "completed",
        description: "14:19 • -A$17.45",
        date: new Date("2024-07-03T14:19:00"),
        merchantIcon: "GC",
        iconColor: "#FB923C",
      },
      {
        userId: thomasId,
        merchant: "Grogan's Castle Lounge",
        amount: "-28.00",
        currency: "AUD",
        originalAmount: "-15.40",
        originalCurrency: "EUR",
        category: "Food & Drink",
        status: "completed",
        description: "13:42 • -A$28.00",
        date: new Date("2024-07-03T13:42:00"),
        merchantIcon: "GC",
        iconColor: "#FB923C",
      },
      {
        userId: thomasId,
        merchant: "Centra",
        amount: "-6.18",
        currency: "AUD",
        originalAmount: "-3.40",
        originalCurrency: "EUR",
        category: "Food & Drink",
        status: "completed",
        description: "10:16 • -A$6.18",
        date: new Date("2024-07-03T10:16:00"),
        merchantIcon: "CE",
        iconColor: "#FB923C",
      },
      {
        userId: thomasId,
        merchant: "Uber Dublin",
        amount: "-29.82",
        currency: "AUD",
        originalAmount: "-16.40",
        originalCurrency: "EUR",
        category: "Transport",
        status: "completed",
        description: "22:05 • -A$29.82",
        date: new Date("2024-07-02T22:05:00"),
        merchantIcon: "UD",
        iconColor: "#0066CC",
      },
      {
        userId: thomasId,
        merchant: "The Church Café Bar",
        amount: "-34.91",
        currency: "AUD",
        originalAmount: "-19.20",
        originalCurrency: "EUR",
        category: "Food & Drink",
        status: "completed",
        description: "20:11 • -A$34.91",
        date: new Date("2024-07-02T20:11:00"),
        merchantIcon: "TC",
        iconColor: "#FB923C",
      },
      {
        userId: thomasId,
        merchant: "The Church Café Bar",
        amount: "-26.55",
        currency: "AUD",
        originalAmount: "-14.60",
        originalCurrency: "EUR",
        category: "Food & Drink",
        status: "completed",
        description: "19:29 • -A$26.55",
        date: new Date("2024-07-02T19:29:00"),
        merchantIcon: "TC",
        iconColor: "#FB923C",
      },
      {
        userId: thomasId,
        merchant: "The Church Café Bar",
        amount: "-50.55",
        currency: "AUD",
        originalAmount: "-27.80",
        originalCurrency: "EUR",
        category: "Food & Drink",
        status: "completed",
        description: "18:54 • -A$50.55",
        date: new Date("2024-07-02T18:54:00"),
        merchantIcon: "TC",
        iconColor: "#FB923C",
      },
      {
        userId: thomasId,
        merchant: "Spar",
        amount: "-5.27",
        currency: "AUD",
        originalAmount: "-2.90",
        originalCurrency: "EUR",
        category: "Food & Drink",
        status: "completed",
        description: "15:02 • -A$5.27",
        date: new Date("2024-07-02T15:02:00"),
        merchantIcon: "SP",
        iconColor: "#FB923C",
      },
      {
        userId: thomasId,
        merchant: "Gravity Bar Guinness",
        amount: "-20.00",
        currency: "AUD",
        originalAmount: "-11.00",
        originalCurrency: "EUR",
        category: "Food & Drink",
        status: "completed",
        description: "13:26 • -A$20.00",
        date: new Date("2024-07-02T13:26:00"),
        merchantIcon: "GB",
        iconColor: "#FB923C",
      },
      {
        userId: thomasId,
        merchant: "Guinness Storehouse",
        amount: "-90.91",
        currency: "AUD",
        originalAmount: "-50.00",
        originalCurrency: "EUR",
        category: "Food & Drink",
        status: "completed",
        description: "11:42 • -A$90.91",
        date: new Date("2024-07-02T11:42:00"),
        merchantIcon: "GS",
        iconColor: "#FB923C",
      },
      {
        userId: thomasId,
        merchant: "Butlers Café",
        amount: "-11.09",
        currency: "AUD",
        originalAmount: "-6.10",
        originalCurrency: "EUR",
        category: "Food & Drink",
        status: "completed",
        description: "09:08 • -A$11.09",
        date: new Date("2024-07-02T09:08:00"),
        merchantIcon: "BC",
        iconColor: "#FB923C",
      },
      {
        userId: thomasId,
        merchant: "Uber Dublin",
        amount: "-22.91",
        currency: "AUD",
        originalAmount: "-12.60",
        originalCurrency: "EUR",
        category: "Transport",
        status: "completed",
        description: "21:01 • -A$22.91",
        date: new Date("2024-07-01T21:01:00"),
        merchantIcon: "UD",
        iconColor: "#0066CC",
      },
      {
        userId: thomasId,
        merchant: "The Brazen Head",
        amount: "-31.27",
        currency: "AUD",
        originalAmount: "-17.20",
        originalCurrency: "EUR",
        category: "Food & Drink",
        status: "completed",
        description: "20:14 • -A$31.27",
        date: new Date("2024-07-01T20:14:00"),
        merchantIcon: "TB",
        iconColor: "#FB923C",
      },
      {
        userId: thomasId,
        merchant: "The Brazen Head",
        amount: "-16.00",
        currency: "AUD",
        originalAmount: "-8.80",
        originalCurrency: "EUR",
        category: "Food & Drink",
        status: "completed",
        description: "19:42 • -A$16.00",
        date: new Date("2024-07-01T19:42:00"),
        merchantIcon: "TB",
        iconColor: "#FB923C",
      },
      {
        userId: thomasId,
        merchant: "The Brazen Head",
        amount: "-29.09",
        currency: "AUD",
        originalAmount: "-16.00",
        originalCurrency: "EUR",
        category: "Food & Drink",
        status: "completed",
        description: "19:09 • -A$29.09",
        date: new Date("2024-07-01T19:09:00"),
        merchantIcon: "TB",
        iconColor: "#FB923C",
      },
      {
        userId: thomasId,
        merchant: "The Stag's Head",
        amount: "-22.91",
        currency: "AUD",
        originalAmount: "-12.60",
        originalCurrency: "EUR",
        category: "Food & Drink",
        status: "completed",
        description: "14:07 • -A$22.91",
        date: new Date("2024-07-01T14:07:00"),
        merchantIcon: "TS",
        iconColor: "#FB923C",
      },
      {
        userId: thomasId,
        merchant: "The Stag's Head",
        amount: "-17.82",
        currency: "AUD",
        originalAmount: "-9.80",
        originalCurrency: "EUR",
        category: "Food & Drink",
        status: "completed",
        description: "13:39 • -A$17.82",
        date: new Date("2024-07-01T13:39:00"),
        merchantIcon: "TS",
        iconColor: "#FB923C",
      },
      {
        userId: thomasId,
        merchant: "The Stag's Head",
        amount: "-44.55",
        currency: "AUD",
        originalAmount: "-24.50",
        originalCurrency: "EUR",
        category: "Food & Drink",
        status: "completed",
        description: "13:06 • -A$44.55",
        date: new Date("2024-07-01T13:06:00"),
        merchantIcon: "TS",
        iconColor: "#FB923C",
      },
      {
        userId: thomasId,
        merchant: "Spar",
        amount: "-5.65",
        currency: "AUD",
        originalAmount: "-3.10",
        originalCurrency: "EUR",
        category: "Food & Drink",
        status: "completed",
        description: "11:14 • -A$5.65",
        date: new Date("2024-07-01T11:14:00"),
        merchantIcon: "SP",
        iconColor: "#FB923C",
      },
      {
        userId: thomasId,
        merchant: "Butlers Chocolate Café",
        amount: "-10.18",
        currency: "AUD",
        originalAmount: "-5.60",
        originalCurrency: "EUR",
        category: "Food & Drink",
        status: "completed",
        description: "09:32 • -A$10.18",
        date: new Date("2024-07-01T09:32:00"),
        merchantIcon: "BC",
        iconColor: "#FB923C",
      },
      {
        userId: thomasId,
        merchant: "Uber Dublin",
        amount: "-25.82",
        currency: "AUD",
        originalAmount: "-14.20",
        originalCurrency: "EUR",
        category: "Transport",
        status: "completed",
        description: "23:48 • -A$25.82",
        date: new Date("2024-06-30T23:48:00"),
        merchantIcon: "UD",
        iconColor: "#0066CC",
      },
      {
        userId: thomasId,
        merchant: "The Temple Bar Pub",
        amount: "-33.96",
        currency: "AUD",
        originalAmount: "-18.70",
        originalCurrency: "EUR",
        category: "Food & Drink",
        status: "completed",
        description: "23:11 • -A$33.96",
        date: new Date("2024-06-30T23:11:00"),
        merchantIcon: "TT",
        iconColor: "#FB923C",
      },
      {
        userId: thomasId,
        merchant: "The Temple Bar Pub",
        amount: "-11.64",
        currency: "AUD",
        originalAmount: "-6.40",
        originalCurrency: "EUR",
        category: "Food & Drink",
        status: "completed",
        description: "22:32 • -A$11.64",
        date: new Date("2024-06-30T22:32:00"),
        merchantIcon: "TT",
        iconColor: "#FB923C",
      },
      {
        userId: thomasId,
        merchant: "The Temple Bar Pub",
        amount: "-33.96",
        currency: "AUD",
        originalAmount: "-18.70",
        originalCurrency: "EUR",
        category: "Food & Drink",
        status: "completed",
        description: "21:57 • -A$33.96",
        date: new Date("2024-06-30T21:57:00"),
        merchantIcon: "TT",
        iconColor: "#FB923C",
      },
      {
        userId: thomasId,
        merchant: "The Temple Bar Pub",
        amount: "-33.96",
        currency: "AUD",
        originalAmount: "-18.70",
        originalCurrency: "EUR",
        category: "Food & Drink",
        status: "completed",
        description: "21:19 • -A$33.96",
        date: new Date("2024-06-30T21:19:00"),
        merchantIcon: "TT",
        iconColor: "#FB923C",
      },
      {
        userId: thomasId,
        merchant: "The Temple Bar Pub",
        amount: "-33.96",
        currency: "AUD",
        originalAmount: "-18.70",
        originalCurrency: "EUR",
        category: "Food & Drink",
        status: "completed",
        description: "20:43 • -A$33.96",
        date: new Date("2024-06-30T20:43:00"),
        merchantIcon: "TT",
        iconColor: "#FB923C",
      },
      {
        userId: thomasId,
        merchant: "Tesco Express",
        amount: "-5.82",
        currency: "AUD",
        originalAmount: "-3.20",
        originalCurrency: "EUR",
        category: "Food & Drink",
        status: "completed",
        description: "14:11 • -A$5.82",
        date: new Date("2024-06-30T14:11:00"),
        merchantIcon: "TE",
        iconColor: "#FB923C",
      },
      {
        userId: thomasId,
        merchant: "FREE NOW Dublin",
        amount: "-58.18",
        currency: "AUD",
        originalAmount: "-32.00",
        originalCurrency: "EUR",
        category: "Transport",
        status: "completed",
        description: "12:52 • -A$58.18",
        date: new Date("2024-06-30T12:52:00"),
        merchantIcon: "FN",
        iconColor: "#0066CC",
      },
      {
        userId: thomasId,
        merchant: "Park Corner Brasserie",
        amount: "-25.63",
        currency: "AUD",
        originalAmount: "-12.30",
        originalCurrency: "GBP",
        category: "Food & Drink",
        status: "completed",
        description: "23:06 • -A$25.63",
        date: new Date("2024-06-29T23:06:00"),
        merchantIcon: "PC",
        iconColor: "#FB923C",
      },
      {
        userId: thomasId,
        merchant: "Artesian Marylebone",
        amount: "-80.21",
        currency: "AUD",
        originalAmount: "-38.50",
        originalCurrency: "GBP",
        category: "Food & Drink",
        status: "completed",
        description: "21:43 • -A$80.21",
        date: new Date("2024-06-29T21:43:00"),
        merchantIcon: "AM",
        iconColor: "#FB923C",
      },
      {
        userId: thomasId,
        merchant: "34 Mayfair",
        amount: "-795.25",
        currency: "AUD",
        originalAmount: "-382.12",
        originalCurrency: "GBP",
        category: "Food & Drink",
        status: "completed",
        description: "19:24 • -A$795.25",
        date: new Date("2024-06-29T19:24:00"),
        merchantIcon: "3M",
        iconColor: "#FB923C",
      },
      {
        userId: thomasId,
        merchant: "Boots",
        amount: "-5.42",
        currency: "AUD",
        originalAmount: "-2.60",
        originalCurrency: "GBP",
        category: "Health",
        status: "completed",
        description: "17:55 • -A$5.42",
        date: new Date("2024-06-29T17:55:00"),
        merchantIcon: "BO",
        iconColor: "#FFFFFF",
      },
      {
        userId: thomasId,
        merchant: "Waitrose Park Lane",
        amount: "-54.17",
        currency: "AUD",
        originalAmount: "-26.00",
        originalCurrency: "GBP",
        category: "Food & Drink",
        status: "completed",
        description: "16:21 • -A$54.17",
        date: new Date("2024-06-29T16:21:00"),
        merchantIcon: "WP",
        iconColor: "#FB923C",
      },
      {
        userId: thomasId,
        merchant: "British Museum Shop",
        amount: "-31.25",
        currency: "AUD",
        originalAmount: "-15.00",
        originalCurrency: "GBP",
        category: "Shopping",
        status: "completed",
        description: "15:07 • -A$31.25",
        date: new Date("2024-06-29T15:07:00"),
        merchantIcon: "BM",
        iconColor: "#DC2626",
      },
      {
        userId: thomasId,
        merchant: "British Museum",
        amount: "-62.50",
        currency: "AUD",
        originalAmount: "-30.00",
        originalCurrency: "GBP",
        category: "Entertainment",
        status: "completed",
        description: "13:22 • -A$62.50",
        date: new Date("2024-06-29T13:22:00"),
        merchantIcon: "BM",
        iconColor: "#9333EA",
      },
      {
        userId: thomasId,
        merchant: "Transport for London",
        amount: "-6.04",
        currency: "AUD",
        originalAmount: "-2.90",
        originalCurrency: "GBP",
        category: "Transport",
        status: "completed",
        description: "12:02 • -A$6.04",
        date: new Date("2024-06-29T12:02:00"),
        merchantIcon: "TFL",
        iconColor: "#0066CC",
      },
      {
        userId: thomasId,
        merchant: "Pret A Manger Strand",
        amount: "-7.92",
        currency: "AUD",
        originalAmount: "-3.80",
        originalCurrency: "GBP",
        category: "Food & Drink",
        status: "completed",
        description: "11:31 • -A$7.92",
        date: new Date("2024-06-29T11:31:00"),
        merchantIcon: "PA",
        iconColor: "#FB923C",
      },
      {
        userId: thomasId,
        merchant: "Parcafé Dorchester",
        amount: "-10.00",
        currency: "AUD",
        originalAmount: "-4.80",
        originalCurrency: "GBP",
        category: "Food & Drink",
        status: "completed",
        description: "10:43 • -A$10.00",
        date: new Date("2024-06-29T10:43:00"),
        merchantIcon: "PD",
        iconColor: "#FB923C",
      },
      {
        userId: thomasId,
        merchant: "Notes Coffee",
        amount: "-18.75",
        currency: "AUD",
        originalAmount: "-9.00",
        originalCurrency: "GBP",
        category: "Food & Drink",
        status: "completed",
        description: "08:27 • -A$18.75",
        date: new Date("2024-06-29T08:27:00"),
        merchantIcon: "NC",
        iconColor: "#FB923C",
      },
      {
        userId: thomasId,
        merchant: "Transport for London",
        amount: "-6.04",
        currency: "AUD",
        originalAmount: "-2.90",
        originalCurrency: "GBP",
        category: "Transport",
        status: "completed",
        description: "23:58 • -A$6.04",
        date: new Date("2024-06-28T23:58:00"),
        merchantIcon: "TFL",
        iconColor: "#0066CC",
      },
      {
        userId: thomasId,
        merchant: "White Horse Soho",
        amount: "-28.33",
        currency: "AUD",
        originalAmount: "-13.60",
        originalCurrency: "GBP",
        category: "Food & Drink",
        status: "completed",
        description: "22:07 • -A$28.33",
        date: new Date("2024-06-28T22:07:00"),
        merchantIcon: "WH",
        iconColor: "#FB923C",
      },
      {
        userId: thomasId,
        merchant: "White Horse Soho",
        amount: "-28.33",
        currency: "AUD",
        originalAmount: "-13.60",
        originalCurrency: "GBP",
        category: "Food & Drink",
        status: "completed",
        description: "21:44 • -A$28.33",
        date: new Date("2024-06-28T21:44:00"),
        merchantIcon: "WH",
        iconColor: "#FB923C",
      },
      {
        userId: thomasId,
        merchant: "White Horse Soho",
        amount: "-14.17",
        currency: "AUD",
        originalAmount: "-6.80",
        originalCurrency: "GBP",
        category: "Food & Drink",
        status: "completed",
        description: "21:09 • -A$14.17",
        date: new Date("2024-06-28T21:09:00"),
        merchantIcon: "WH",
        iconColor: "#FB923C",
      },
      {
        userId: thomasId,
        merchant: "The Ivy Asia Mayfair",
        amount: "-483.33",
        currency: "AUD",
        originalAmount: "-232.00",
        originalCurrency: "GBP",
        category: "Food & Drink",
        status: "completed",
        description: "19:36 • -A$483.33",
        date: new Date("2024-06-28T19:36:00"),
        merchantIcon: "TI",
        iconColor: "#FB923C",
      },
      {
        userId: thomasId,
        merchant: "Sainsbury's Local",
        amount: "-6.67",
        currency: "AUD",
        originalAmount: "-3.20",
        originalCurrency: "GBP",
        category: "Food & Drink",
        status: "completed",
        description: "17:12 • -A$6.67",
        date: new Date("2024-06-28T17:12:00"),
        merchantIcon: "SL",
        iconColor: "#FB923C",
      },
      {
        userId: thomasId,
        merchant: "Harrods",
        amount: "-1416.67",
        currency: "AUD",
        originalAmount: "-680.00",
        originalCurrency: "GBP",
        category: "Shopping",
        status: "completed",
        description: "15:47 • -A$1416.67",
        date: new Date("2024-06-28T15:47:00"),
        merchantIcon: "HA",
        iconColor: "#DC2626",
      },
      {
        userId: thomasId,
        merchant: "Park Corner Brasserie",
        amount: "-25.63",
        currency: "AUD",
        originalAmount: "-12.30",
        originalCurrency: "GBP",
        category: "Food & Drink",
        status: "completed",
        description: "13:34 • -A$25.63",
        date: new Date("2024-06-28T13:34:00"),
        merchantIcon: "PC",
        iconColor: "#FB923C",
      },
      {
        userId: thomasId,
        merchant: "Transport for London",
        amount: "-6.04",
        currency: "AUD",
        originalAmount: "-2.90",
        originalCurrency: "GBP",
        category: "Transport",
        status: "completed",
        description: "12:18 • -A$6.04",
        date: new Date("2024-06-28T12:18:00"),
        merchantIcon: "TFL",
        iconColor: "#0066CC",
      },
      {
        userId: thomasId,
        merchant: "Tesco Express",
        amount: "-3.13",
        currency: "AUD",
        originalAmount: "-1.50",
        originalCurrency: "GBP",
        category: "Food & Drink",
        status: "completed",
        description: "11:02 • -A$3.13",
        date: new Date("2024-06-28T11:02:00"),
        merchantIcon: "TE",
        iconColor: "#FB923C",
      },
      {
        userId: thomasId,
        merchant: "Parcafé Dorchester",
        amount: "-9.38",
        currency: "AUD",
        originalAmount: "-4.50",
        originalCurrency: "GBP",
        category: "Food & Drink",
        status: "completed",
        description: "10:16 • -A$9.38",
        date: new Date("2024-06-28T10:16:00"),
        merchantIcon: "PD",
        iconColor: "#FB923C",
      },
      {
        userId: thomasId,
        merchant: "Serpentine Lido Café",
        amount: "-30.21",
        currency: "AUD",
        originalAmount: "-14.50",
        originalCurrency: "GBP",
        category: "Food & Drink",
        status: "completed",
        description: "08:19 • -A$30.21",
        date: new Date("2024-06-28T08:19:00"),
        merchantIcon: "SL",
        iconColor: "#FB923C",
      },
      {
        userId: thomasId,
        merchant: "Transport for London",
        amount: "-6.67",
        currency: "AUD",
        originalAmount: "-3.20",
        originalCurrency: "GBP",
        category: "Transport",
        status: "completed",
        description: "23:14 • -A$6.67",
        date: new Date("2024-06-27T23:14:00"),
        merchantIcon: "TFL",
        iconColor: "#0066CC",
      },
      {
        userId: thomasId,
        merchant: "Be At One Islington",
        amount: "-71.25",
        currency: "AUD",
        originalAmount: "-34.20",
        originalCurrency: "GBP",
        category: "Entertainment",
        status: "completed",
        description: "22:32 • -A$71.25",
        date: new Date("2024-06-27T22:32:00"),
        merchantIcon: "BA",
        iconColor: "#9333EA",
      },
      {
        userId: thomasId,
        merchant: "Be At One Islington",
        amount: "-36.67",
        currency: "AUD",
        originalAmount: "-17.60",
        originalCurrency: "GBP",
        category: "Entertainment",
        status: "completed",
        description: "21:47 • -A$36.67",
        date: new Date("2024-06-27T21:47:00"),
        merchantIcon: "BA",
        iconColor: "#9333EA",
      },
      {
        userId: thomasId,
        merchant: "Be At One Islington",
        amount: "-18.33",
        currency: "AUD",
        originalAmount: "-8.80",
        originalCurrency: "GBP",
        category: "Entertainment",
        status: "completed",
        description: "21:11 • -A$18.33",
        date: new Date("2024-06-27T21:11:00"),
        merchantIcon: "BA",
        iconColor: "#9333EA",
      },
      {
        userId: thomasId,
        merchant: "Park Corner Brasserie",
        amount: "-25.63",
        currency: "AUD",
        originalAmount: "-12.30",
        originalCurrency: "GBP",
        category: "Food & Drink",
        status: "completed",
        description: "18:20 • -A$25.63",
        date: new Date("2024-06-27T18:20:00"),
        merchantIcon: "PC",
        iconColor: "#FB923C",
      },
      {
        userId: thomasId,
        merchant: "Dishoom Carnaby",
        amount: "-129.17",
        currency: "AUD",
        originalAmount: "-62.00",
        originalCurrency: "GBP",
        category: "Food & Drink",
        status: "completed",
        description: "17:22 • -A$129.17",
        date: new Date("2024-06-27T17:22:00"),
        merchantIcon: "DC",
        iconColor: "#FB923C",
      },
      {
        userId: thomasId,
        merchant: "Starbucks Oxford Street",
        amount: "-6.88",
        currency: "AUD",
        originalAmount: "-3.30",
        originalCurrency: "GBP",
        category: "Food & Drink",
        status: "completed",
        description: "16:04 • -A$6.88",
        date: new Date("2024-06-27T16:04:00"),
        merchantIcon: "SO",
        iconColor: "#FB923C",
      },
      {
        userId: thomasId,
        merchant: "Transport for London",
        amount: "-6.04",
        currency: "AUD",
        originalAmount: "-2.90",
        originalCurrency: "GBP",
        category: "Transport",
        status: "completed",
        description: "14:21 • -A$6.04",
        date: new Date("2024-06-27T14:21:00"),
        merchantIcon: "TFL",
        iconColor: "#0066CC",
      },
      {
        userId: thomasId,
        merchant: "Hard Rock Cafe Old Park Lane",
        amount: "-59.38",
        currency: "AUD",
        originalAmount: "-28.50",
        originalCurrency: "GBP",
        category: "Food & Drink",
        status: "completed",
        description: "12:46 • -A$59.38",
        date: new Date("2024-06-27T12:46:00"),
        merchantIcon: "HR",
        iconColor: "#FB923C",
      },
      {
        userId: thomasId,
        merchant: "Tesco Express",
        amount: "-3.96",
        currency: "AUD",
        originalAmount: "-1.90",
        originalCurrency: "GBP",
        category: "Food & Drink",
        status: "completed",
        description: "10:56 • -A$3.96",
        date: new Date("2024-06-27T10:56:00"),
        merchantIcon: "TE",
        iconColor: "#FB923C",
      },
      {
        userId: thomasId,
        merchant: "Transport for London",
        amount: "-11.67",
        currency: "AUD",
        originalAmount: "-5.60",
        originalCurrency: "GBP",
        category: "Transport",
        status: "completed",
        description: "09:08 • -A$11.67",
        date: new Date("2024-06-27T09:08:00"),
        merchantIcon: "TFL",
        iconColor: "#0066CC",
      },
      {
        userId: thomasId,
        merchant: "Gail's Bakery Seymour Place",
        amount: "-20.42",
        currency: "AUD",
        originalAmount: "-9.80",
        originalCurrency: "GBP",
        category: "Food & Drink",
        status: "completed",
        description: "08:12 • -A$20.42",
        date: new Date("2024-06-27T08:12:00"),
        merchantIcon: "GB",
        iconColor: "#FB923C",
      },
      {
        userId: thomasId,
        merchant: "Money added via Apple Pay",
        amount: "20833.33",
        currency: "AUD",
        originalAmount: "10000.00",
        originalCurrency: "GBP",
        category: "Top Up",
        status: "completed",
        description: "09:12 • +A$20833.33",
        date: new Date("2024-06-25T09:12:00"),
        merchantIcon: "apple",
        iconColor: "#4ADE80",
      },
      {
        userId: thomasId,
        merchant: "Money added via Apple Pay",
        amount: "20833.33",
        currency: "AUD",
        originalAmount: null,
        originalCurrency: null,
        category: "Top Up",
        status: "completed",
        description: "09:12 • +A$20833.33",
        date: new Date("2024-06-25T09:12:00"),
        merchantIcon: "apple",
        iconColor: "#4ADE80",
      },
    ];

    transactions.forEach(transaction => {
      const id = randomUUID();
      this.transactions.set(id, { ...transaction, id });
    });

    // Create crypto assets
    const cryptoAssets: CryptoAsset[] = [
      {
        id: "bitcoin",
        symbol: "BTC",
        name: "Bitcoin",
        price: "178792.00",
        change24h: "0.25",
        chartData: [
          { time: 1, value: 175000 },
          { time: 2, value: 176500 },
          { time: 3, value: 178000 },
          { time: 4, value: 179200 },
          { time: 5, value: 178792 }
        ],
        icon: "₿",
      },
      {
        id: "ethereum",
        symbol: "ETH",
        name: "Ethereum",
        price: "6635.63",
        change24h: "-0.71",
        chartData: [
          { time: 1, value: 6800 },
          { time: 2, value: 6750 },
          { time: 3, value: 6700 },
          { time: 4, value: 6650 },
          { time: 5, value: 6635.63 }
        ],
        icon: "Ξ",
      },
      {
        id: "0x",
        symbol: "XCN",
        name: "0x Protocol",
        price: "0.45",
        change24h: "23.44",
        icon: "0x",
      },
      {
        id: "polygon",
        symbol: "MATIC",
        name: "Polygon",
        price: "1.23",
        change24h: "4.14",
        icon: "⬟",
      },
      {
        id: "polkadot",
        symbol: "POL",
        name: "Polkadot",
        price: "8.92",
        change24h: "4.10",
        icon: "●",
      },
      {
        id: "golem",
        symbol: "GLM",
        name: "Golem",
        price: "0.34",
        change24h: "3.40",
        icon: "G",
      },
      {
        id: "amp",
        symbol: "AMP",
        name: "Amp",
        price: "0.012",
        change24h: "3.19",
        icon: "A",
      },
      {
        id: "qtum",
        symbol: "QI",
        name: "Qtum",
        price: "4.56",
        change24h: "2.64",
        icon: "Q",
      },
      {
        id: "cronos",
        symbol: "CRO",
        name: "Cronos",
        price: "0.18",
        change24h: "2.39",
        icon: "C",
      },
      {
        id: "loot",
        symbol: "AGLD",
        name: "Adventure Gold",
        price: "2.34",
        change24h: "2.36",
        icon: "L",
      },
    ];

    cryptoAssets.forEach(asset => {
      this.cryptoAssets.set(asset.id, asset);
    });
  }

  async getUser(id: string): Promise<User | undefined> {
    return this.users.get(id);
  }

  async getUserByUsername(username: string): Promise<User | undefined> {
    return Array.from(this.users.values()).find(
      (user) => user.username === username,
    );
  }

  async createUser(insertUser: InsertUser): Promise<User> {
    const id = randomUUID();
    const user: User = { ...insertUser, id, createdAt: new Date() };
    this.users.set(id, user);
    return user;
  }

  async getUserTransactions(userId: string): Promise<Transaction[]> {
    return Array.from(this.transactions.values())
      .filter(transaction => transaction.userId === userId)
      .sort((a, b) => new Date(b.date).getTime() - new Date(a.date).getTime());
  }

  async createTransaction(insertTransaction: InsertTransaction): Promise<Transaction> {
    const id = randomUUID();
    const transaction: Transaction = { ...insertTransaction, id, date: new Date() };
    this.transactions.set(id, transaction);
    return transaction;
  }

  async getUserCards(userId: string): Promise<Card[]> {
    return Array.from(this.cards.values())
      .filter(card => card.userId === userId);
  }

  async createCard(insertCard: InsertCard): Promise<Card> {
    const id = randomUUID();
    const card: Card = { ...insertCard, id, createdAt: new Date() };
    this.cards.set(id, card);
    return card;
  }

  async getCryptoAssets(): Promise<CryptoAsset[]> {
    return Array.from(this.cryptoAssets.values());
  }

  async updateCryptoAsset(asset: CryptoAsset): Promise<CryptoAsset> {
    this.cryptoAssets.set(asset.id, asset);
    return asset;
  }
}

export const storage = new MemStorage();